### ISSUE TITLE
[Docs] move `master` docs into `other versions` in the website menu

### ISSUE THREAD

**Issue by rwaight** [elastic/docs#1779] opened 2020-03-20 14:09 UTC
In order to improve navigation on the [Elastic Stack and Product Documentation](https://www.elastic.co/guide/index.html) site, it would be helpful to put `master` into the `other versions` section of the navigation menu.

Currently the `master` version of the documentation is available in the main version menu on the site.  This can cause confusion when reading about capabilities and configurations of currently available products, since the `master` version is preliminary documentation.

**Comment by lcawl** [comment] 2020-03-20 14:31
Probably you could make the same case for any .x pre-release content (like 7.x branches).

**Comment by gtback** [comment] 2020-04-29 20:37
This can be done on a per-book basis by changing the `live:` key in conf.yaml. For the ~50% of books that are versioned with the stack (see the [`stacklive` variable](https://github.com/elastic/docs/blob/master/conf.yaml#L60)`, this would happen for all of them at once, though in an edge case we could make a one-off exception for a single book.

Alternatively, we could change the order so the "current" book is at the top, followed by older, still-maintained branches, followed by `master`.

**Comment by dedemorton** [comment] 2020-04-29 21:24
There's a similar issue where we started a discussion this here: https://github.com/elastic/docs/issues/349

**Comment by gtback** [comment] 2020-04-30 18:42
Also related: #1480

**Comment by gtback** [comment] 2020-05-15 16:05
Looking closer, I think this might actually be a duplicate of #1480, so I'm going to close this one and we can continue the discussion there.

**Closed by gtback** 2020-05-15 16:05 UTC
Labels: enhancement, versions
