### ISSUE TITLE
Automatically generate mini-ToCs

### ISSUE THREAD

**Issue by kellyemurphy** [elastic/docs#1452] opened 2019-11-25 19:17 UTC
Right now, we are currently creating and maintaining the mini-ToCs (aka "glue" text) manually. This leads to inconsistency and incorrect entries. See the [ECE](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-administering-deployments.html) for an example - look at the difference between the bulleted links on the page and those in the right navigation. 

It would be great if this was somehow automatically generated when the book gets built. Is that possible?

**Comment by debadair** [comment] 2020-04-30 23:26
Duplicate of #https://github.com/elastic/docs/issues/324

**Closed by debadair** 2020-04-30 23:26 UTC
Labels: enhancement
