### ISSUE TITLE
Text in tables sometimes overflows right-side nav

### ISSUE THREAD

**Issue by dedemorton** [elastic/docs#138] opened 2016-12-15 20:51 UTC
Multiple users have reported layout problems with web pages that have tables. The text in the table overflows the right-side nav. I thought this problem was limited to tables with strings that are too long to fit in the table cell, but it appears that the problem is more extensive than I realized.

Here are a couple of examples:

![image](https://cloud.githubusercontent.com/assets/14206422/21241469/9cb93aaa-c2c4-11e6-96f7-08a8fce7acdd.png)

![image](https://cloud.githubusercontent.com/assets/14206422/21241600/2c72835e-c2c5-11e6-8fe0-bb92cf3fbc2a.png)

**Comment by clintongormley** [comment] 2016-12-16 16:26
The problem is long text which can't be broken, eg  in https://www.elastic.co/guide/en/kibana/4.5/kibana-server-properties.html you have the tilemap URL which defaults to 

    https://tiles.elastic.co/v1/default/{z}/{x}/{y}.png?    
    elastic_tile_service_tos=agree&my_app_name=kibana

That's setting the minimum width of the table. This has to be fixed on a case by case basis

**Closed by clintongormley** 2016-12-16 16:26 UTC
Labels: bug, docs
