### ISSUE TITLE
"xmllint" --nonet --noout --valid "/out/html_docs/README.xml" returned non-zero exit status 4

### ISSUE THREAD

**Issue by pouledodue** [elastic/docs#909] opened 2019-06-01 23:08 UTC
`./build_docs --doc README.asciidoc --pdf`

```INFO:build_docs:a2x: ERROR: "xmllint" --nonet --noout --valid "/out/html_docs/README.xml" returned non-zero exit status 4```

**Comment by nik9000** [comment] 2019-06-05 19:40
PDF is on my list but not super high to be honest.

**Comment by pouledodue** [comment] 2019-06-05 19:45
I need a fix before 2024

**Comment by debadair** [comment] 2019-09-24 23:41
Duplicate ofhttps://github.com/elastic/docs/issues/61

**Comment by gtback** [comment] 2020-05-14 21:42
We don't support the `--pdf` option anymore (as of #1394). As mentioned there, if we support it in the future we'll be rewriting it anyway.

**Closed by gtback** 2020-05-14 21:42 UTC
Labels: enhancement
