### ISSUE TITLE
Inconsistent style in definition lists with multiple paragraphs 

### ISSUE THREAD

**Issue by nrichers** [elastic/docs#126] opened 2016-10-29 02:46 UTC
In the following example, only the text with checkmarks is displayed in the correct style used for definition lists that have single paragraphs. The rest of the text is not displayed correctly and uses a larger font. 

![image](https://cloud.githubusercontent.com/assets/15148011/19825084/fde15828-9d29-11e6-90f4-7bef2d53168e.png)

This was an problem discussed in the #techpubs channel a while back and there was a reference someone made to an existing issue. I couldn't find the issue in this repo, though, so I opened this one here. If an issue already exists, please close this one. 

I did some very basic preliminary investigation and it looks like the troublesome multi-paragraph text is enclosed in `<p class="simpara">` `</p>` tags inside the `<dd></dd>` tags that have a different CSS style than when just plain <dd></dd> tags are used. If you manually remove the `<p>` taga in the Chrome dev tools (1), the style is correct: 

![image](https://cloud.githubusercontent.com/assets/15148011/19826589/5c407b42-9d43-11e6-8218-1777b6b23ff0.png)

That's as far as I got.

**Comment by lcawl** [comment] 2017-04-24 15:14
I have encountered similar issues when there are admonition blocks inside definition lists, which I guess is the same as having multiple paragraphs in definition lists. 

![badformat](https://cloud.githubusercontent.com/assets/26471269/25344076/daa289c2-28c5-11e7-884f-96321d1c67e2.jpg)

As Nik mentioned above, the problematic formatting seems to be a <p class="simpara">.  I can work around the problem by making the admonition blocks peers to the definition list items (i.e. no longer nested under them), but it makes it less clear what their context is.

**Comment by jonasll** [comment] 2020-03-06 00:07
I couldn't reproduce this, closing for sanity.

**Closed by jonasll** 2020-03-06 00:07 UTC
Labels: bug, help wanted
